spring:
  application:
    name: example-edu-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/example_edu_db}
      database: example_edu_db
      auto-index-creation: true

jwt:
  private:
    key: classpath:keys/private-key.pem
  public:
    key: classpath:keys/public-key.pem
  settings:
    expiration-in-seconds: 3600
